Schedule field is working fix working.
canaris-in/canidesk pull request #112
Opened 2023-06-21 07:15 UTC by rajeshcanaris

Schedule field is working fix working.

2023-06-21 08:36 UTC, Shubham40Bears requested changes

2023-06-21 08:36 UTC, Shubham40Bears commented on app/Console/Commands/AutoReport.php
> +        // dd('done');
remove this commented out dd and $this->info

2023-06-21 08:36 UTC, Shubham40Bears commented on app/Console/Commands/AutoReport.php
> +            $this->info($settings->frequency);
remove all these infos

2023-06-21 08:36 UTC, Shubham40Bears commented on app/Console/Commands/AutoReport.php
> +        //    dd('done');
remove this dd

2023-06-21 08:36 UTC, Shubham40Bears commented on app/Console/Commands/AutoReport.php
> +                $message->from('rajeshcanaris@gmail.com','[ Canidesk Report ]');
change this from url to the MAIL_USERNAME variable from env file

2023-06-22 11:01 UTC, umar-ashrfy requested changes

2023-06-22 11:01 UTC, umar-ashrfy commented on app/Console/Commands/AutoReport.php
> +            $data = array('name'=>"Example");
report.pdf should be

Report_{Weekly}_{start_date}_{end_date}.pdf

2023-06-22 11:01 UTC, umar-ashrfy commented on app/Console/Commands/AutoReport.php
> +            $data = array('name'=>"Example");
Example => Canidesk

2023-06-22 13:07 UTC, umar-ashrfy approved these changes

2023-06-22 13:08 UTC, merged