fix graph and fix filters
canaris-in/canidesk pull request #40
Opened 2023-05-31 11:20 UTC by rajeshcanaris

2023-06-05 10:03 UTC, umar-ashrfy approved these changes

2023-06-14 13:17 UTC, Shubham40Bears commented on app/Http/Controllers/SettingsCani.php
> +<?php
Rename this file to ReportSettingsController

2023-06-14 13:17 UTC, Shubham40Bears commented on app/Http/Controllers/SlaReportController.php
> +    // public function settings(){
Remove unused code

2023-06-15 04:24 UTC, rajeshcanaris commented
Its Fix sir


On Wed, 14 Jun 2023 at 18:47, Shubham40Bears ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/Http/Controllers/SettingsCani.php
> <https://github.com/canaris-in/canidesk/pull/40#discussion_r1229605189>:
>
> > @@ -0,0 +1,44 @@
> +<?php
>
> Rename this file to ReportSettingsController
> ------------------------------
>
> In app/Http/Controllers/SlaReportController.php
> <https://github.com/canaris-in/canidesk/pull/40#discussion_r1229605682>:
>
> > @@ -14,4 +15,18 @@ public function slaReport()
>          $tickets = Conversation::with('user', 'conversationCustomField.custom_field', 'conversationCategory','conversationPriority')->get();
>          return view('sla/report', compact('tickets'));
>      }
> +    // public function settings(){
>
> Remove unused code
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/canaris-in/canidesk/pull/40#pullrequestreview-1479424042>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A76A3M2YFOZLN3B5ILJAGQ3XLG2YJANCNFSM6AAAAAAYVJ2VGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-19 07:05 UTC, umar-ashrfy requested changes

2023-06-19 07:05 UTC, umar-ashrfy commented on Modules/Reports/Resources/views/partials/menu.blade.php
> +        <li><a href="/reports/settings">Settings</a></li>
Change the Link to be dynamic. Check above links

2023-06-19 07:05 UTC, umar-ashrfy commented on app/Console/Commands/AutoReport.php
> +use App\Settingssla;
Change the class name from Settingssla to SLASetting

2023-06-19 07:05 UTC, umar-ashrfy commented on app/Console/Commands/AutoReport.php
> +    protected $description = 'this command is uesd to send email automatically';
uesd -> used

2023-06-19 07:05 UTC, umar-ashrfy commented on database/migrations/2023_06_15_174122_create_settingsslas_table.php
> +        Schema::create('settingsslas', function (Blueprint $table) {
sla_setting

2023-06-19 07:05 UTC, umar-ashrfy commented on app/Http/Controllers/ReportSettingsController.php
> +      $settings=Settingssla::orderBy('id', 'desc')->first();
Change the class name from Settingssla to SLASetting

2023-06-19 07:05 UTC, umar-ashrfy commented on app/Console/Commands/AutoReport.php
> +        $settings=Settingssla::orderBy('id', 'desc')->first();
Change the class name from Settingssla to SLASetting

2023-06-19 07:05 UTC, umar-ashrfy commented on app/Http/Controllers/ReportSettingsController.php
> +    $settingslas=new Settingssla;
$settingslas=new Settingssla;

Refactor
$slaSettings = new SLASetting();

2023-06-19 07:05 UTC, umar-ashrfy commented on resources/views/layouts/app.blade.php
> +                                                        <li class="Container-flweb-notification-more">
Have a space in between two css classes
Container-flweb-notification-more. -> container-fl web-notification-more

2023-06-20 05:13 UTC, Shubham40Bears requested changes

2023-06-20 05:13 UTC, Shubham40Bears commented on app/Console/Commands/AutoReport.php
> +            ('hello i am rajesh rathod')->attach('/home/rathod/git/TaskSecond/canidesk/report.pdf');
change this to storage path of laravel

2023-06-20 05:13 UTC, Shubham40Bears commented on app/Console/Commands/AutoReport.php
> +        $message->to('rr7049908@gmail.com', 'Tutorials Point')->subject
this should be dynamic

2023-06-20 13:10 UTC, merged